name: symphony_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Lemonada
      fonts:
        - asset: assets/fonts/Lemonada/Lemonada-Bold.ttf
        - asset: assets/fonts/Lemonada/Lemonada-Light.ttf
        - asset: assets/fonts/Lemonada/Lemonada-Regular.ttf
        - asset: assets/fonts/Lemonada/Lemonada-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
